name: Build and Deploy
on:
  push:
    branches:
      - main
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2 # If you're using actions/checkout@v2 you must set persist-credentials to false in most cases for the deployment to work correctly.
        with:
          persist-credentials: false
          lfs: true

      - name: Install and Build
        run: |
          npm ci
          npm run export
      - name: Add CNAME
        run: |
          echo "miia.website" >> __sapper__/export/CNAME

      - name: webfactory/ssh-agent
        uses: webfactory/ssh-agent@v0.4.0
        with:
          ssh-private-key: ${{ secrets.DEPLOY_KEY }}

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@releases/v3
        with:
          BRANCH: gh-pages # The branch the action should deploy to.
          FOLDER: __sapper__/export # The folder the action should deploy.
          SSH: true
          GIT_CONFIG_NAME: github-pages-deploy
          GIT_CONFIG_EMAIL: dpongimo@gmail.com
          SINGLE_COMMIT: true
